//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.App_code
{
    using System;
    using System.Collections.Generic;
    
    public partial class cau_hinh
    {
        public int MaCauHinh { get; set; }
        public string TenCauHinh { get; set; }
        public string GiaTri { get; set; }
        public string GiaTriMoRong { get; set; }
    }
}
