//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.App_code
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_gia
    {
        public doc_gia()
        {
            this.muon_tra = new HashSet<muon_tra>();
        }
    
        public int DocGiaID { get; set; }
        public string TenDocGia { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<muon_tra> muon_tra { get; set; }
    }
}
