//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.App_code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class library_managementEntities : DbContext
    {
        public library_managementEntities()
            : base("name=library_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cau_hinh> cau_hinh { get; set; }
        public virtual DbSet<doc_gia> doc_gia { get; set; }
        public virtual DbSet<loai_sach> loai_sach { get; set; }
        public virtual DbSet<ma> mas { get; set; }
        public virtual DbSet<muon_tra> muon_tra { get; set; }
        public virtual DbSet<nguoi_su_dung> nguoi_su_dung { get; set; }
        public virtual DbSet<nha_xuat_ban> nha_xuat_ban { get; set; }
        public virtual DbSet<sach> saches { get; set; }
        public virtual DbSet<tac_gia> tac_gia { get; set; }
        public virtual DbSet<tinh_trang_muon_tra> tinh_trang_muon_tra { get; set; }
        public virtual DbSet<tinh_trang_sach> tinh_trang_sach { get; set; }
    }
}
