//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.App_code
{
    using System;
    using System.Collections.Generic;
    
    public partial class loai_sach
    {
        public loai_sach()
        {
            this.saches = new HashSet<sach>();
        }
    
        public int LoaiSachID { get; set; }
        public string TenLoaiSach { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<sach> saches { get; set; }
    }
}
