//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.App_code
{
    using System;
    using System.Collections.Generic;
    
    public partial class muon_tra
    {
        public int MuonTraID { get; set; }
        public int SachID { get; set; }
        public int DocGiaID { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime NgayHenTra { get; set; }
        public Nullable<bool> GiaHan { get; set; }
        public Nullable<System.DateTime> NgayGiaHan { get; set; }
        public int TinhTrangMuonTraID { get; set; }
    
        public virtual doc_gia doc_gia { get; set; }
        public virtual sach sach { get; set; }
    }
}
