//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.App_code
{
    using System;
    using System.Collections.Generic;
    
    public partial class tac_gia
    {
        public tac_gia()
        {
            this.saches = new HashSet<sach>();
            this.saches1 = new HashSet<sach>();
        }
    
        public int TacGiaID { get; set; }
        public string TenTacGia { get; set; }
        public string Mota { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<sach> saches { get; set; }
        public virtual ICollection<sach> saches1 { get; set; }
    }
}
